// GENERATED BY scripts/gen_types.py — DO NOT EDIT BY HAND.
// Source of truth: assignment_helper/document/schema.py
// Run `python scripts/gen_types.py` after any schema change.
// tests/unit/test_generated_types.py fails if this file is stale.



export interface BoxedBlock {
  readonly kind: 'boxed';
  readonly id: string;
  readonly seed: number;
  readonly children: Array<ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock>;
}

export interface DiagramBlock {
  readonly kind: 'diagram';
  readonly id: string;
  readonly seed: number;
  readonly spec: Array<Record<string, unknown>>;
  readonly height_mm?: number;
}

export interface Document {
  readonly schema_version?: number;
  readonly id: string;
  readonly title?: string;
  readonly blocks?: Array<ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock>;
  readonly style?: Style;
  readonly source_path?: string | null;
}

export interface HandStyle {
  readonly profile?: string;
  readonly ink_colour?: string;
  readonly size_mm?: number;
  readonly slant_deg?: number;
  readonly neatness?: number;
  readonly overrides?: Record<string, number>;
}

export interface InsertBlock {
  readonly op: 'insert';
  readonly index: number;
  readonly block: ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock;
}

export interface MathBlock {
  readonly kind: 'math';
  readonly id: string;
  readonly seed: number;
  readonly latex: string;
  readonly display?: boolean;
}

export interface PaperStyle {
  readonly kind: 'ruled' | 'plain' | 'grid' | 'rough';
  readonly ruling?: 'college' | 'wide' | 'grid5';
  readonly page_size?: 'letter' | 'a4' | 'legal';
  readonly tint?: string;
  readonly rule_colour?: string;
  readonly margin_rule_colour?: string;
  readonly grain?: number;
  readonly aging?: number;
}

export interface ProseBlock {
  readonly kind: 'prose';
  readonly id: string;
  readonly seed: number;
  readonly text: string;
  readonly emphasis?: 'normal' | 'heading' | 'answer';
}

export interface RemoveBlock {
  readonly op: 'remove';
  readonly block_id: string;
}

export interface ReplaceBlock {
  readonly op: 'replace';
  readonly block_id: string;
  readonly block: ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock;
}

export interface SetStyle {
  readonly op: 'style';
  readonly style: Style;
}

export interface SpacerBlock {
  readonly kind: 'spacer';
  readonly id: string;
  readonly seed: number;
  readonly height_mm: number;
}

export interface Style {
  readonly paper?: PaperStyle;
  readonly hand?: HandStyle;
  readonly margins_mm?: [number, number, number, number];
  readonly preview_dpi?: number;
  readonly export_dpi?: number;
}

export interface Document {
  readonly schema_version?: number;
  readonly id: string;
  readonly title?: string;
  readonly blocks?: Array<ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock>;
  readonly style?: Style;
  readonly source_path?: string | null;
}

export interface Delta {
  readonly parent_version: number;
  readonly ops: Array<InsertBlock | RemoveBlock | ReplaceBlock | SetStyle>;
  readonly origin?: 'user' | 'ai' | 'file' | 'server';
}

export interface Snapshot {
  readonly version: number;
  readonly document: Document;
}

export interface Problem {
  readonly scope: 'block' | 'page' | 'app';
  readonly code: string;
  readonly message: string;
  readonly block_id?: string | null;
  readonly detail?: string | null;
}

/** The discriminated union every render module switches on. */
export type Block = ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock;
export type BlockKind = Block['kind'];
export type Op = InsertBlock | RemoveBlock | ReplaceBlock | SetStyle;
