#!/usr/bin/env python3
"""Generate web/src/types/document.d.ts from the pydantic document schema.

The generated file is COMMITTED, and tests/unit/test_generated_types.py asserts it is
up to date. The schema is a frozen contract (plan §3): it changes on `dev`, via the
lead, never inside a strand branch. Regenerating is how a schema change reaches the
TypeScript half — there is no second, hand-maintained definition to drift.

    python scripts/gen_types.py          # write
    python scripts/gen_types.py --check  # exit 1 if stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from assignment_helper.document.schema import (  # noqa: E402
    Delta,
    Document,
    Problem,
    Snapshot,
)

OUT = ROOT / "web/src/types/document.d.ts"

HEADER = """// GENERATED BY scripts/gen_types.py — DO NOT EDIT BY HAND.
// Source of truth: assignment_helper/document/schema.py
// Run `python scripts/gen_types.py` after any schema change.
// tests/unit/test_generated_types.py fails if this file is stale.

"""


def ts_type(node: dict, defs: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return repr(node["const"]).replace("'", "'")
    if "enum" in node:
        return " | ".join(f"'{v}'" for v in node["enum"])
    if "anyOf" in node or "oneOf" in node:
        parts = [ts_type(s, defs) for s in node.get("anyOf") or node["oneOf"]]
        return " | ".join(dict.fromkeys(parts))
    t = node.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = node.get("items")
        if isinstance(items, list):  # fixed-length tuple
            return "[" + ", ".join(ts_type(i, defs) for i in items) + "]"
        if node.get("prefixItems"):
            return "[" + ", ".join(ts_type(i, defs) for i in node["prefixItems"]) + "]"
        return f"Array<{ts_type(items, defs) if items else 'unknown'}>"
    if t == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra, defs)}>"
        return "Record<string, unknown>"
    return "unknown"


def emit_interface(name: str, node: dict, defs: dict) -> str:
    required = set(node.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, sub in node.get("properties", {}).items():
        # The discriminants must be REQUIRED in TS even though pydantic gives them a
        # default — an optional discriminant does not narrow, and every render module
        # switches on block.kind.
        opt = "" if prop in required or prop in ("kind", "op") else "?"
        lines.append(f"  readonly {prop}{opt}: {ts_type(sub, defs)};")
    lines.append("}")
    return "\n".join(lines)


def emit_union(name: str, node: dict, defs: dict) -> str:
    parts = [ts_type(s, defs) for s in node["oneOf"]]
    return f"export type {name} = {' | '.join(parts)};"


def generate() -> str:
    out = [HEADER]
    seen: dict[str, dict] = {}
    roots = []
    for model in (Document, Delta, Snapshot, Problem):
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        seen.update(schema.pop("$defs", {}))
        roots.append((model.__name__, schema))

    # $defs first (dependency order does not matter for TS interfaces), then roots.
    for name, node in sorted(seen.items()):
        if "oneOf" in node and "properties" not in node:
            out.append(emit_union(name, node, seen))
        else:
            out.append(emit_interface(name, node, seen))
    for name, node in roots:
        out.append(emit_interface(name, node, seen))

    # Hand-maintained aliases that the render path depends on and the schema cannot express.
    out.append(
        "/** The discriminated union every render module switches on. */\n"
        "export type Block = ProseBlock | MathBlock | DiagramBlock | BoxedBlock | SpacerBlock;\n"
        "export type BlockKind = Block['kind'];\n"
        "export type Op = InsertBlock | RemoveBlock | ReplaceBlock | SetStyle;"
    )
    return "\n\n".join(out) + "\n"


def main() -> int:
    text = generate()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"STALE: {OUT} does not match the schema. Run: python scripts/gen_types.py")
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
